version: '3.8'
services:
  weather:
    build:
      context: .
      dockerfile: weather_service/Dockerfile

  agent:
    build:
      context: .
      dockerfile: agent_service/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"

  agent_client:
    build:
      context: .
      dockerfile: agent_client/Dockerfile
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - agent
